Resources:
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.connectionsTableName}
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
        - AttributeName: connectionId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  SnippetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.snippetsTableName}
      AttributeDefinitions:
        - AttributeName: snippetId
          AttributeType: S
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
        - AttributeName: snippetId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
